"""GROMACS production-grade MD protocol.

This module owns the protocol definition — the sequence of stages,
the deterministic ``.mdp`` content for each stage, and the
command-line arguments for every ``gmx`` invocation. It does **not**
execute subprocesses; the runner in :mod:`biolab_runners.gromacs.runner`
consumes the plan and orchestrates execution.

The protocol is the canonical "oral_amp" pipeline recipe:

1. **Topology** — ``gmx pdb2gmx -f input.pdb -o processed.gro``
2. **Box** — ``gmx editconf -f processed.gro -o boxed.gro -bt cubic -d <buffer>``
3. **Solvation** — ``gmx solvate -cp boxed.gro -cs spc216.gro -o solvated.gro -p topol.top``
4. **Ions** — ``gmx grompp -f ions.mdp -c solvated.gro -p topol.top -o ions.tpr`` then
   ``gmx genion -s ions.tpr -o ions.gro -p topol.top -pname NA -nname CL -neutral -conc 0.15``
   with the ``SOL`` group selection sent via subprocess stdin (no shell)
5. **Minimization** — ``gmx grompp -f min.mdp -c ions.gro -p topol.top``
   then ``gmx mdrun -deffnm min [-cpi min.cpt] [-append]``
   (steepest descent, max 50 000 iterations)
6. **NVT equilibration** — 100 ps with ``-DPOSRES`` flag set so position restraints are applied
   (the ``[ position_restraints ]`` topology directive is NOT re-emitted in the .mdp because
   it must live in the topology file to take effect — see GROMACS manual §5.7.1)
7. **NPT equilibration** — 100 ps with ``-DPOSRES`` flag set
8. **Production** — default 200 ns, NPT, no restraints; ``-cpi`` is added **only** when
   ``prod.cpt`` exists on disk (the "no duplicate start path" rule)

The ``.mdp`` content is generated by the four ``generate_*_mdp``
functions. The content is **byte-deterministic** for a given input —
two calls with the same parameters produce byte-identical strings.
This is a test invariant (see ``tests/test_gromacs_protocol.py``).

All MD .mdp files use ``constraints = h-bonds`` and
``constraint-algorithm = lincs`` at ``dt = 0.002`` — the canonical
GROMACS recipe for 2 fs hydrogen-bond-constrained MD. Production uses
``v-rescale`` / ``nose-hoover`` + ``parrinello-rahman`` (NPT); NVT/NPT
equilibration uses ``v-rescale`` (Berendsen's stochastic noise is
unwanted for the equilibration phase, but v-rescale produces a correct
canonical ensemble without the ergodicity issues of weak-coupling
thermostats).

Per-replica deterministic seeds (``gen-seed = replica_index + 1``)
ensure each replica produces a reproducible trajectory while keeping
replicas diverse. Set ``gen-seed = -1`` for non-deterministic runs
(the ``runner`` does NOT pass ``-1``; the .mdp value is used as-is).
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import TYPE_CHECKING

from biolab_runners.gromacs.paths import GromacsFiles

if TYPE_CHECKING:
    from pathlib import Path

    from biolab_runners.gromacs.config import GromacsProtocolConfig


__all__ = [
    "GENION_INPUT",
    "ProtocolStage",
    "StageKind",
    "StageSpec",
    "build_commands",
    "build_stage_plan",
    "generate_equil_npt_mdp",
    "generate_equil_nvt_mdp",
    "generate_minimization_mdp",
    "generate_production_mdp",
    "ions_mdp_content",
    "stage_outputs_for",
]


class StageKind(StrEnum):
    """Categorical classification of a protocol stage.

    Used by the runner to decide which subprocess flow to invoke
    (``gmx pdb2gmx`` is one-shot; ``gmx mdrun`` is checkpoint-
    resumable). Distinct from :class:`ProtocolStage`, which carries
    the per-stage ``-deffnm`` and mdp filename.
    """

    TOPOLOGY = "topology"
    BOX = "box"
    SOLVATE = "solvate"
    IONS = "ions"
    MINIMIZE = "minimize"
    EQUIL_NVT = "equil_nvt"
    EQUIL_NPT = "equil_npt"
    PRODUCTION = "production"


# Genion needs a group selection ("SOL\n" by default — solvent). Sent
# via subprocess stdin so we never need a shell wrapper. This is the
# canonical "noninteractive genion" pattern from the GROMACS manual.
GENION_INPUT = "SOL\n"


# Default position-restraint energy constant for NVT/NPT equilibration.
# 1000 kJ/mol/nm^2 is the conventional value (strong enough to keep
# protein heavy atoms near the minimised coordinates while the solvent
# relaxes around them). The ``[ position_restraints ]`` block lives in
# the topology file (not the .mdp) — the .mdp only sets ``define =
# -DPOSRES`` to enable it.
_DEFAULT_POSRES_K = 1000.0

# Canonical 2 fs timestep (the only value used across all MD .mdp
# files in this protocol). Required for LINCS h-bond constraints.
_TIMESTEP_FS = 2


@dataclass(frozen=True)
class ProtocolStage:
    """One stage in the GROMACS protocol.

    A stage owns its ``-deffnm`` prefix, its ``.mdp`` filename, and
    its :class:`StageKind`. The runner walks a list of these and
    executes each one in order.
    """

    kind: StageKind
    prefix: str
    mdp_filename: str


@dataclass(frozen=True)
class StageSpec:
    """A resolved stage: kind + the on-disk outputs the runner expects.

    The ``outputs`` tuple is the set of filenames that must exist
    for the stage to be considered complete. The runner uses this
    to decide skip-vs-resume before invoking any subprocess.
    """

    stage: ProtocolStage
    outputs: tuple[str, ...]


def _ps_to_steps(duration_ps: int) -> int:
    """Convert ps to integration steps at the canonical 2 fs timestep."""
    return int(duration_ps * 1000 / _TIMESTEP_FS)


def _ns_to_steps(duration_ns: float) -> int:
    """Convert ns to integration steps at the canonical 2 fs timestep."""
    return round(duration_ns * 1_000_000 / _TIMESTEP_FS)


def generate_minimization_mdp(
    max_iterations: int = 50_000,
    *,
    replica_index: int = 0,
) -> str:
    """Generate the deterministic ``.mdp`` content for steepest-descent minimisation.

    The default ``max_iterations=50_000`` matches the S4 spec
    (the historical OpenMM path uses 1 000; the GROMACS protocol
    uses 50 000 to converge solvated systems with 0.15 M ions
    where charge-neutralisation can require thousands of steps).

    The content is byte-deterministic — identical inputs produce
    byte-identical output. Tests assert this with ``==``.

    Args:
        max_iterations: Steepest-descent cap. Must be positive.
        replica_index: 0-indexed replica number. ``gen-seed`` is set
            to ``replica_index + 1`` so each replica produces a
            deterministic-but-different velocity-rescale seed (the
            seed only matters for ``md`` integrator; steepest descent
            ignores it but we keep the field set for consistency).

    Returns:
        The ``.mdp`` file content as a single string.

    Raises:
        ValueError: If ``max_iterations`` is not positive.
    """
    if max_iterations < 1:
        raise ValueError(f"max_iterations must be positive; got {max_iterations}")
    if replica_index < 0:
        raise ValueError(f"replica_index must be non-negative; got {replica_index}")
    return (
        "; Steepest-descent energy minimisation\n"
        "; Generated by biolab-runners (deterministic content)\n"
        "integrator       = steep\n"
        "emtol            = 1000.0\n"
        "emstep           = 0.01\n"
        f"nsteps           = {max_iterations}\n"
        "nstenergy        = 500\n"
        "nstlog           = 500\n"
        "cutoff-scheme    = Verlet\n"
        "nstlist          = 20\n"
        "ns-type          = grid\n"
        "coulombtype      = PME\n"
        "rcoulomb         = 1.0\n"
        "rvdw             = 1.0\n"
        "pme-order        = 4\n"
        "fourierspacing   = 0.12\n"
        "tcoupl           = no\n"
        "pcoupl           = no\n"
        f"gen-seed         = {replica_index + 1}\n"
    )


def generate_equil_nvt_mdp(
    duration_ps: int = 100,
    temperature_k: float = 310.0,
    *,
    replica_index: int = 0,
) -> str:
    """Generate the deterministic ``.mdp`` content for NVT equilibration.

    NVT is the FIRST MD stage after minimisation. As such it is the
    stage that bootstraps velocities from a Maxwell-Boltzmann
    distribution at the target temperature (``gen-vel = yes``,
    ``gen-temp = {temperature_k}``). NPT and production inherit
    velocities from the previous stage's .gro/.cpt and so do NOT
    set ``gen-vel`` (a regression that sets ``gen-vel = yes`` in
    NPT or production would silently REPLACE the equilibrated
    velocities with fresh Maxwell-Boltzmann draws on every fresh
    start, defeating equilibration).

    Resume behaviour: ``gmx grompp -t <checkpoint>`` reads velocities
    from the .cpt and IGNORES ``gen-vel`` (GROMACS semantic — see
    the manual §Table 5.4: "gen-vel: ignored if -t is provided").
    So the same .mdp is correct for both fresh start and resume;
    the runner adds ``-t <cpt>`` to the grompp invocation only
    when a checkpoint exists on disk.

    NVT uses a v-rescale thermostat with the ``-DPOSRES`` flag
    set so position restraints (declared in the topology, not
    the .mdp) are applied while the solvent thermalises around
    the protein.

    The ``[ position_restraints ]`` topology directive is **not**
    emitted here — that section lives in the topology file and
    is activated by the ``-DPOSRES`` preprocessor define.

    Args:
        duration_ps: NVT equilibration length in ps. Must be positive.
        temperature_k: Target temperature in Kelvin. Must be positive.
        replica_index: 0-indexed replica number (sets ``gen-seed``).

    Returns:
        The ``.mdp`` file content as a single string.

    Raises:
        ValueError: If ``duration_ps`` or ``temperature_k`` are not positive.
    """
    if duration_ps < 1:
        raise ValueError(f"duration_ps must be positive; got {duration_ps}")
    if temperature_k <= 0:
        raise ValueError(f"temperature_k must be positive; got {temperature_k}")
    if replica_index < 0:
        raise ValueError(f"replica_index must be non-negative; got {replica_index}")
    nsteps = _ps_to_steps(duration_ps)
    return (
        "; NVT equilibration (v-rescale thermostat, position restraints in topology)\n"
        "; Generated by biolab-runners (deterministic content)\n"
        "define           = -DPOSRES\n"
        "integrator       = md\n"
        f"dt               = {_TIMESTEP_FS / 1000}\n"
        f"nsteps           = {nsteps}\n"
        "nstenergy        = 500\n"
        "nstlog           = 500\n"
        "nstxtcout        = 5000\n"
        "cutoff-scheme    = Verlet\n"
        "nstlist          = 20\n"
        "ns-type          = grid\n"
        "coulombtype      = PME\n"
        "rcoulomb         = 1.0\n"
        "rvdw             = 1.0\n"
        "pme-order        = 4\n"
        "fourierspacing   = 0.12\n"
        "tcoupl           = v-rescale\n"
        "tc-grps          = System\n"
        f"ref-t            = {temperature_k}\n"
        "tau-t            = 0.1\n"
        "pcoupl           = no\n"
        "constraints      = h-bonds\n"
        "constraint-algorithm = lincs\n"
        "lincs-iter       = 1\n"
        "lincs-order      = 4\n"
        "gen-vel          = yes\n"
        f"gen-temp         = {temperature_k}\n"
        f"gen-seed         = {replica_index + 1}\n"
    )


def generate_equil_npt_mdp(
    duration_ps: int = 100,
    temperature_k: float = 310.0,
    pressure_bar: float = 1.0,
    *,
    replica_index: int = 0,
) -> str:
    """Generate the deterministic ``.mdp`` content for NPT equilibration.

    NPT adds a v-rescale thermostat + Berendsen barostat on top of
    NVT. Position restraints remain activated via ``-DPOSRES`` (the
    restraints themselves live in the topology, not here).

    NPT inherits velocities from the previous stage's .gro/.cpt;
    it does NOT set ``gen-vel`` (only the first MD stage, NVT,
    bootstraps velocities from a Maxwell-Boltzmann distribution).
    On resume from a .cpt, ``gmx grompp -t <cpt>`` ignores any
    ``gen-vel`` setting (GROMACS manual §Table 5.4), so the same
    .mdp is correct for both fresh start and resume.

    Args:
        duration_ps: NPT equilibration length in ps. Must be positive.
        temperature_k: Target temperature in Kelvin. Must be positive.
        pressure_bar: Target pressure in bar. Must be positive.
        replica_index: 0-indexed replica number (sets ``gen-seed``).

    Returns:
        The ``.mdp`` file content as a single string.

    Raises:
        ValueError: If any argument is not positive.
    """
    if duration_ps < 1:
        raise ValueError(f"duration_ps must be positive; got {duration_ps}")
    if temperature_k <= 0:
        raise ValueError(f"temperature_k must be positive; got {temperature_k}")
    if pressure_bar <= 0:
        raise ValueError(f"pressure_bar must be positive; got {pressure_bar}")
    if replica_index < 0:
        raise ValueError(f"replica_index must be non-negative; got {replica_index}")
    nsteps = _ps_to_steps(duration_ps)
    return (
        "; NPT equilibration (v-rescale + Berendsen barostat, position restraints in topology)\n"
        "; Generated by biolab-runners (deterministic content)\n"
        "define           = -DPOSRES\n"
        "integrator       = md\n"
        f"dt               = {_TIMESTEP_FS / 1000}\n"
        f"nsteps           = {nsteps}\n"
        "nstenergy        = 500\n"
        "nstlog           = 500\n"
        "nstxtcout        = 5000\n"
        "cutoff-scheme    = Verlet\n"
        "nstlist          = 20\n"
        "ns-type          = grid\n"
        "coulombtype      = PME\n"
        "rcoulomb         = 1.0\n"
        "rvdw             = 1.0\n"
        "pme-order        = 4\n"
        "fourierspacing   = 0.12\n"
        "tcoupl           = v-rescale\n"
        "tc-grps          = System\n"
        f"ref-t            = {temperature_k}\n"
        "tau-t            = 0.1\n"
        "pcoupl           = berendsen\n"
        "pcoupltype       = isotropic\n"
        f"ref-p            = {pressure_bar}\n"
        "tau-p            = 1.0\n"
        "compressibility  = 4.5e-5\n"
        "constraints      = h-bonds\n"
        "constraint-algorithm = lincs\n"
        "lincs-iter       = 1\n"
        "lincs-order      = 4\n"
        f"gen-seed         = {replica_index + 1}\n"
    )


def generate_production_mdp(
    duration_ns: float = 200.0,
    temperature_k: float = 310.0,
    pressure_bar: float = 1.0,
    *,
    replica_index: int = 0,
) -> str:
    """Generate the deterministic ``.mdp`` content for production MD.

    Production removes position restraints (no ``-DPOSRES`` define),
    switches to a Nose-Hoover thermostat + Parrinello-Rahman
    barostat for proper NPT sampling, and uses a 2 fs timestep
    with LINCS h-bond constraints.

    XTC (compressed trajectory), EDR (energy), and the human-readable
    log are written automatically by ``gmx mdrun`` based on the
    ``nst*`` intervals. The default 200 ns matches the S4 spec.

    Like NPT, production inherits velocities from the previous
    stage's .gro/.cpt and does NOT set ``gen-vel`` — only NVT (the
    first MD stage) bootstraps velocities from a Maxwell-Boltzmann
    distribution. On resume, ``grompp -t <cpt>`` ignores any
    ``gen-vel`` setting, so the same .mdp is correct for both
    fresh start and resume.

    Args:
        duration_ns: Production length in nanoseconds. Must be positive.
        temperature_k: Target temperature in Kelvin. Must be positive.
        pressure_bar: Target pressure in bar. Must be positive.
        replica_index: 0-indexed replica number (sets ``gen-seed``).

    Returns:
        The ``.mdp`` file content as a single string.

    Raises:
        ValueError: If any argument is not positive.
    """
    if duration_ns <= 0:
        raise ValueError(f"duration_ns must be positive; got {duration_ns}")
    if temperature_k <= 0:
        raise ValueError(f"temperature_k must be positive; got {temperature_k}")
    if pressure_bar <= 0:
        raise ValueError(f"pressure_bar must be positive; got {pressure_bar}")
    if replica_index < 0:
        raise ValueError(f"replica_index must be non-negative; got {replica_index}")
    nsteps = _ns_to_steps(duration_ns)
    return (
        "; Production MD (NPT, no restraints, Nose-Hoover + Parrinello-Rahman)\n"
        "; Generated by biolab-runners (deterministic content)\n"
        "integrator       = md\n"
        f"dt               = {_TIMESTEP_FS / 1000}\n"
        f"nsteps           = {nsteps}\n"
        "nstenergy        = 5000\n"
        "nstlog           = 5000\n"
        "nstxtcout        = 50000\n"
        "cutoff-scheme    = Verlet\n"
        "nstlist          = 20\n"
        "ns-type          = grid\n"
        "coulombtype      = PME\n"
        "rcoulomb         = 1.0\n"
        "rvdw             = 1.0\n"
        "pme-order        = 4\n"
        "fourierspacing   = 0.12\n"
        "tcoupl           = nose-hoover\n"
        "tc-grps          = System\n"
        f"ref-t            = {temperature_k}\n"
        "tau-t            = 0.5\n"
        "pcoupl           = parrinello-rahman\n"
        "pcoupltype       = isotropic\n"
        f"ref-p            = {pressure_bar}\n"
        "tau-p            = 5.0\n"
        "compressibility  = 4.5e-5\n"
        "constraints      = h-bonds\n"
        "constraint-algorithm = lincs\n"
        "lincs-iter       = 1\n"
        "lincs-order      = 4\n"
        f"gen-seed         = {replica_index + 1}\n"
    )


# Canonical ions .mdp (the smallest possible content for genion prep).
# GROMACS requires grompp to produce a .tpr before genion can read it;
# this is the dummy .mdp that satisfies the grompp step.
_IONS_MDP_CONTENT = (
    "; Dummy .mdp for grompp before genion\n"
    "integrator       = steep\n"
    "nsteps           = 0\n"
    "cutoff-scheme    = Verlet\n"
    "ns-type          = grid\n"
    "coulombtype      = PME\n"
    "rcoulomb         = 1.0\n"
    "rvdw             = 1.0\n"
    "tcoupl           = no\n"
    "pcoupl           = no\n"
    "gen-seed         = 1\n"
)


def ions_mdp_content() -> str:
    """Return the dummy .mdp content used to build ``ions.tpr`` for genion.

    A constant string — the only thing the .mdp needs to specify is
    a zero-step integrator (we don't run dynamics here; grompp only
    needs to write the .tpr so genion can read it).
    """
    return _IONS_MDP_CONTENT


def build_stage_plan() -> tuple[ProtocolStage, ...]:
    """Return the canonical ordered list of protocol stages.

    Order matters: the topology must precede the box, the box the
    solvation, the solvation the ions, and the ions the minimisation.
    The minimisation precedes both equilibration stages, and the
    NPT equilibration precedes the production run.

    The runner iterates this list, deciding per-stage whether to
    skip (outputs already exist), resume (``.cpt`` exists), or
    start fresh.
    """
    return (
        ProtocolStage(StageKind.TOPOLOGY, "topol", GromacsFiles.TOPOLOGY_TOP),
        ProtocolStage(StageKind.BOX, "box", ""),
        ProtocolStage(StageKind.SOLVATE, "solvate", GromacsFiles.TOPOLOGY_TOP),
        ProtocolStage(StageKind.IONS, "ions", GromacsFiles.IONS_MDP),
        ProtocolStage(
            StageKind.MINIMIZE,
            GromacsFiles.MIN_PREFIX,
            GromacsFiles.MIN_MDP,
        ),
        ProtocolStage(
            StageKind.EQUIL_NVT,
            GromacsFiles.NVT_PREFIX,
            GromacsFiles.NVT_MDP,
        ),
        ProtocolStage(
            StageKind.EQUIL_NPT,
            GromacsFiles.NPT_PREFIX,
            GromacsFiles.NPT_MDP,
        ),
        ProtocolStage(
            StageKind.PRODUCTION,
            GromacsFiles.PROD_PREFIX,
            GromacsFiles.PROD_MDP,
        ),
    )


def stage_outputs_for(kind: StageKind, prefix: str) -> tuple[str, ...]:
    """Return the full canonical on-disk outputs for a stage.

    For setup stages (topology, box, solvate, ions) the outputs are
    the single artifact ``gmx`` writes at the end of the command.
    For MD stages (minimize, equil, production) the outputs are the
    full ``-deffnm`` set: ``.tpr`` (compiled input), ``.gro`` (final
    coordinates — input to the next stage), ``.cpt`` (resume key),
    ``.edr`` (energy), ``.log`` (text log), ``.xtc`` (compressed
    trajectory), and ``.trr`` (full-precision trajectory).

    **This is the full set** — for the disk-fallback check the
    runner uses :func:`stage_minimum_outputs` (a STRICT SUBSET)
    because some artifacts are only written on long runs (e.g.
    ``.xtc`` / ``.trr`` only fire after ``nstxtcout`` steps; the
    ``.cpt`` is intermittent). Forbidding them in the fallback
    would force the runner to re-run every short simulation.
    """
    if kind in (StageKind.MINIMIZE, StageKind.EQUIL_NVT, StageKind.EQUIL_NPT, StageKind.PRODUCTION):
        return GromacsFiles.stage_outputs(prefix)
    setup_outputs: dict[StageKind, tuple[str, ...]] = {
        StageKind.TOPOLOGY: (GromacsFiles.TOPOLOGY_TOP, GromacsFiles.TOPOLOGY_GRO),
        StageKind.BOX: (GromacsFiles.BOX_GRO,),
        StageKind.SOLVATE: (GromacsFiles.SOLVATED_GRO,),
        StageKind.IONS: (GromacsFiles.IONIZED_TPR, GromacsFiles.IONIZED_GRO),
    }
    return setup_outputs[kind]


# Minimum required on-disk outputs for the disk-fallback path to
# consider a stage complete. These are the artifacts that ``gmx``
# writes UNCONDITIONALLY when the stage finishes (or fails) — the
# .tpr is the compiled input (always written), the .gro is the
# final coordinates (always written unless mdrun is killed before
# it can flush), and the .edr + .log are written at every
# ``nstenergy`` / ``nstlog`` interval (small enough to fire even
# for short runs).
#
# The ``.cpt`` is intermittent (only written at ``nstcheckpoint``)
# and the ``.xtc`` / ``.trr`` are intermittent (only written at
# ``nstxtcout`` / ``nstxout``). Forbidding them in the fallback
# would force the runner to re-run every short simulation, which
# defeats the purpose of the fallback. The runner still re-checks
# ``.cpt`` separately (via :func:`_checkpoint_for`) when deciding
# fresh-vs-resume, so missing .cpt correctly forces a fresh start.
_MINIMUM_OUTPUTS: dict[StageKind, tuple[str, ...]] = {
    StageKind.TOPOLOGY: (GromacsFiles.TOPOLOGY_TOP, GromacsFiles.TOPOLOGY_GRO),
    StageKind.BOX: (GromacsFiles.BOX_GRO,),
    StageKind.SOLVATE: (GromacsFiles.SOLVATED_GRO,),
    StageKind.IONS: (GromacsFiles.IONIZED_TPR, GromacsFiles.IONIZED_GRO),
    # MD stages: tpr + gro + edr + log are guaranteed.
    StageKind.MINIMIZE: ("min.tpr", "min.gro", "min.edr", "min.log"),
    StageKind.EQUIL_NVT: ("nvt.tpr", "nvt.gro", "nvt.edr", "nvt.log"),
    StageKind.EQUIL_NPT: ("npt.tpr", "npt.gro", "npt.edr", "npt.log"),
    StageKind.PRODUCTION: ("prod.tpr", "prod.gro", "prod.edr", "prod.log"),
}


def stage_minimum_outputs(kind: StageKind, prefix: str = "") -> tuple[str, ...]:  # noqa: ARG001
    """Return the minimum on-disk outputs required for the disk fallback.

    This is a STRICT SUBSET of :func:`stage_outputs_for`. Used by
    the runner's disk-fallback check (``_outputs_complete_on_disk``)
    — see that function's docstring for the rationale.

    The ``prefix`` parameter is accepted for API symmetry with
    :func:`stage_outputs_for` but is not currently used (the
    minimum set is fixed by stage kind). Reserved for future
    customisation where callers can register their own minimum
    output sets per ``-deffnm``.
    """
    return _MINIMUM_OUTPUTS[kind]


def build_stage_plan_resolved() -> tuple[StageSpec, ...]:
    """Return the stage plan with outputs pre-resolved.

    Convenience for tests and the runner's skip-vs-resume decision.
    """
    return tuple(
        StageSpec(stage=stage, outputs=stage_outputs_for(stage.kind, stage.prefix))
        for stage in build_stage_plan()
    )


def _setup_topology_commands(
    config: GromacsProtocolConfig,
) -> list[list[str]]:
    """Build the ``gmx pdb2gmx`` command for the TOPOLOGY stage.

    Empty list (``[]``) signals that the TOPOLOGY stage is a
    no-op — the runner skips ``pdb2gmx`` and uses a
    caller-supplied prebuilt topology / coordinates pair
    (staged into ``topol.top`` / ``processed.gro`` by
    :func:`stage_prebuilt_topology`).

    The prebuilt condition is the existence of
    ``config.prebuilt_topology`` AND
    ``config.prebuilt_coordinates`` (both, per the config
    validator). The runner reads this flag from the
    command list and skips the stage accordingly.
    """
    if config.prebuilt_topology and config.prebuilt_coordinates:
        # Prebuilt mode — ``pdb2gmx`` is skipped.
        return []
    return [
        [
            "gmx",
            "pdb2gmx",
            "-f",
            config.input_pdb,
            "-o",
            GromacsFiles.TOPOLOGY_GRO,
            "-p",
            GromacsFiles.TOPOLOGY_TOP,
            "-ff",
            config.force_field,
            "-water",
            config.water_model,
            "-ignh",
        ]
    ]


def stage_prebuilt_topology(
    config: GromacsProtocolConfig,
    work_dir: Path,
) -> dict[str, str]:
    """Materialise the caller-supplied prebuilt files into canonical names.

    Returns a dict mapping ``topology`` / ``coordinates`` to
    absolute source paths so the runner can bind them into
    the stage manifest for provenance. The destination files
    are written atomically via ``shutil.copy2`` (no shell,
    no text rewriting — the prebuilt ``.top`` and ``.gro``
    are byte-identical to the source).

    Args:
        config: Protocol config (must have BOTH
            ``prebuilt_topology`` and ``prebuilt_coordinates``
            set; the runner calls this only after validating
            the pair).
        work_dir: The runner's work directory.

    Returns:
        ``{"topology": str, "coordinates": str, "sha256_topology": str, "sha256_coordinates": str}``
        — the absolute SOURCE paths and their digests (so the
        manifest binds the prebuilt source, not the staged
        copy).

    Raises:
        FileNotFoundError: When either source path is missing.
        ValueError: When the prebuilt pair is incomplete.
    """
    import shutil
    from pathlib import Path as _Path

    if not (config.prebuilt_topology and config.prebuilt_coordinates):
        raise ValueError(
            "stage_prebuilt_topology called with incomplete prebuilt pair; "
            "the runner must check the config validator before calling"
        )
    src_top = _Path(config.prebuilt_topology)
    src_xyz = _Path(config.prebuilt_coordinates)
    if not src_top.is_file():
        raise FileNotFoundError(f"prebuilt topology not found: {src_top}")
    if not src_xyz.is_file():
        raise FileNotFoundError(f"prebuilt coordinates not found: {src_xyz}")

    dst_top = work_dir / GromacsFiles.TOPOLOGY_TOP
    dst_xyz = work_dir / GromacsFiles.TOPOLOGY_GRO
    work_dir.mkdir(parents=True, exist_ok=True)

    shutil.copy2(src_top, dst_top)
    shutil.copy2(src_xyz, dst_xyz)

    # Compute digests on the SOURCE (the prebuilt files are
    # immutable as far as this runner is concerned; the runner
    # binds the source digest, not the staged copy's).
    from biolab_runners.provenance import compute_file_digest

    return {
        "topology": str(src_top),
        "coordinates": str(src_xyz),
        "sha256_topology": compute_file_digest(src_top) or "",
        "sha256_coordinates": compute_file_digest(src_xyz) or "",
    }


def _setup_box_commands(config: GromacsProtocolConfig) -> list[list[str]]:
    """``gmx editconf -d <buffer>`` sets the buffer between solute and box edge.

    The field is named ``box_buffer_nm`` (the distance from solute
    to box edge) — NOT the box edge length itself. ``gmx editconf -d``
    takes the buffer; for a cubic box the edge length is then
    ``protein_extent + 2 * buffer``.
    """
    return [
        [
            "gmx",
            "editconf",
            "-f",
            GromacsFiles.TOPOLOGY_GRO,
            "-o",
            GromacsFiles.BOX_GRO,
            "-bt",
            "cubic",
            "-d",
            f"{config.box_buffer_nm}",
        ]
    ]


def _setup_solvate_commands() -> list[list[str]]:
    return [
        [
            "gmx",
            "solvate",
            "-cp",
            GromacsFiles.BOX_GRO,
            "-cs",
            "spc216.gro",
            "-o",
            GromacsFiles.SOLVATED_GRO,
            "-p",
            GromacsFiles.TOPOLOGY_TOP,
        ]
    ]


def _setup_ions_commands(config: GromacsProtocolConfig) -> list[list[str]]:
    """Two-step ions setup: grompp then genion.

    grompp produces ``ions.tpr`` from the dummy .mdp + solvated
    structure; genion then neutralises the system to
    ``config.ion_concentration_m`` molar and writes ``ions.gro``.

    Genion is noninteractive — the ``SOL`` group selection is sent
    via subprocess stdin by the runner (``input=GENION_INPUT``).
    Never use ``sh -c "echo SOL | gmx genion ..."`` (shell injection
    risk + platform-dependent quoting).
    """
    return [
        [
            "gmx",
            "grompp",
            "-f",
            GromacsFiles.IONS_MDP,
            "-c",
            GromacsFiles.SOLVATED_GRO,
            "-p",
            GromacsFiles.TOPOLOGY_TOP,
            "-o",
            GromacsFiles.IONIZED_TPR,
            "-maxwarn",
            "1",
        ],
        [
            "gmx",
            "genion",
            "-s",
            GromacsFiles.IONIZED_TPR,
            "-o",
            GromacsFiles.IONIZED_GRO,
            "-p",
            GromacsFiles.TOPOLOGY_TOP,
            "-pname",
            "NA",
            "-nname",
            "CL",
            "-neutral",
            "-conc",
            f"{config.ion_concentration_m}",
        ],
    ]


def _input_gro_for(stage: ProtocolStage) -> str:
    """Return the ``-c`` argument for the next stage's grompp.

    Returns a RELATIVE path — ``gmx grompp`` resolves it against
    the process cwd (which the runner sets to ``work_dir``). Using
    a relative path keeps the protocol container-friendly: the
    same protocol works whether the operator mounts the work
    directory at ``/work``, ``/home/antonio/runs``, or any other
    path inside the container. Absolute paths would hard-code the
    host mount point and break across container runtimes.

    Each MD stage takes its starting coordinates from the previous
    stage's ``.gro`` output. On resume, the ``.cpt`` carries the
    positions internally and is passed via ``-t <cpt>`` (see
    :func:`_grompp_command`); the ``-c`` argument is the previous
    stage's .gro regardless (grompp reads positions from the .cpt
    when both are provided).
    """
    prev_stage_inputs: dict[StageKind, str] = {
        StageKind.MINIMIZE: GromacsFiles.IONIZED_GRO,
        StageKind.EQUIL_NVT: f"{GromacsFiles.MIN_PREFIX}.gro",
        StageKind.EQUIL_NPT: f"{GromacsFiles.NVT_PREFIX}.gro",
        StageKind.PRODUCTION: f"{GromacsFiles.NPT_PREFIX}.gro",
    }
    return prev_stage_inputs[stage.kind]


def _grompp_command(
    stage: ProtocolStage,
    checkpoint_path: str | None,
) -> list[str]:
    """Build the ``gmx grompp`` command for an MD stage.

    All paths are RELATIVE — ``gmx grompp`` resolves them against
    the process cwd (which the runner sets to ``work_dir``). This
    keeps the protocol container-friendly (see
    :func:`_input_gro_for` for the rationale).

    The ``-maxwarn 1`` allows grompp to proceed past the most
    common non-fatal warning ("LINCS relative constraint deviation
    is large") which is benign for short equilibration steps.

    When resuming from a ``.cpt`` we additionally pass ``-t <cpt>``
    (relative to cwd) so grompp preserves velocities / state from
    the checkpoint. The ``-c`` argument is the previous stage's
    ``.gro`` regardless — grompp reads positions from the .cpt
    when both ``-c`` and ``-t`` are provided.

    On resume, grompp IGNORES the ``gen-vel`` setting in the .mdp
    (GROMACS manual §Table 5.4). This is what preserves the
    equilibrated velocities across restart — the NVT .mdp sets
    ``gen-vel = yes`` for the fresh-start case but the runner
    adds ``-t <cpt>`` on resume to keep the velocities that were
    saved to the checkpoint.
    """
    cmd = [
        "gmx",
        "grompp",
        "-f",
        stage.mdp_filename,
        "-c",
        _input_gro_for(stage),
        "-p",
        GromacsFiles.TOPOLOGY_TOP,
        "-o",
        f"{stage.prefix}.tpr",
        "-maxwarn",
        "1",
    ]
    if checkpoint_path:
        # The .cpt path is absolute here (the runner passes an
        # absolute path from Path(work_dir) / GromacsFiles.checkpoint).
        # grompp accepts absolute paths in -t without issue; we
        # only avoid absolute paths for the .mdp/.gro/.tpr args
        # to keep the protocol container-mount-agnostic.
        cmd.extend(["-t", checkpoint_path])
    return cmd


def _mdrun_command(
    stage: ProtocolStage,
    config: GromacsProtocolConfig,
    *,
    checkpoint_path: str | None,
) -> list[str]:
    """Build the ``gmx mdrun`` command for an MD stage.

    The ``-cpi`` flag is included **only** when ``checkpoint_path``
    is not None — the "no duplicate start path" rule from the S4
    spec (GROMACS errors when ``-cpi`` points to a non-existent
    file, so the runner pre-checks and emits the flag only when
    resume is actually possible).

    When resuming (``-cpi`` is present), ``-append`` is also added
    so .edr/.log/.xtc are appended to (the GROMACS default is to
    APPEND when -cpi is used, but we make it explicit so a future
    GROMACS version that flips the default doesn't silently corrupt
    our resumable outputs).

    ``-nt`` is **only** added when ``config.nt_threads > 0``. A
    value of 0 means "let GROMACS auto-detect", which is the
    recommended default — passing ``-nt 1`` would force
    single-threaded even on a 64-core machine, and passing
    ``-nt <auto>`` is not a valid invocation.
    """
    cmd = ["gmx", "mdrun", "-deffnm", stage.prefix]
    if config.nt_threads > 0:
        cmd.extend(["-nt", str(config.nt_threads)])
    if checkpoint_path:
        cmd.extend(["-cpi", checkpoint_path, "-append"])
    if config.extra_mdrun_flags:
        cmd.extend(config.extra_mdrun_flags)
    return cmd


def build_commands(
    stage: ProtocolStage,
    *,
    checkpoint_path: str | None,
    config: GromacsProtocolConfig,
) -> list[list[str]]:
    """Return the ordered list of subprocess invocations for a stage.

    Most stages are a single command; ``IONS`` is two (grompp +
    genion); each MD stage is also two (grompp + mdrun). The runner
    executes them in order; the stage is considered complete only
    after every command in the list returns a zero exit code.

    For MD stages, ``gmx grompp`` is invoked first to compile the
    ``.tpr`` from the ``.mdp`` + previous ``.gro`` (+ optional
    ``.cpt`` for resume), then ``gmx mdrun`` runs the dynamics
    with ``-cpi`` + ``-append`` iff a ``.cpt`` exists.

    Args:
        stage: The protocol stage to build the commands for.
        checkpoint_path: Absolute path to the ``.cpt`` file, or
            ``None`` for a fresh start. Only consulted for MD
            stages (minimize / equil_* / production); ignored
            for setup stages which are always one-shot.
        config: The protocol config (input PDB, force field,
            box buffer, ion concentration, threads, extra mdrun
            flags).

    Returns:
        A list of commands; each command is a list of strings
        suitable for ``subprocess.run`` / ``subprocess.Popen``.
    """
    if stage.kind == StageKind.TOPOLOGY:
        return _setup_topology_commands(config)
    if stage.kind == StageKind.BOX:
        return _setup_box_commands(config)
    if stage.kind == StageKind.SOLVATE:
        return _setup_solvate_commands()
    if stage.kind == StageKind.IONS:
        return _setup_ions_commands(config)
    # MD stages: grompp first (compiles the .tpr from the previous .gro +
    # current .mdp), then mdrun. The .tpr is the input to mdrun, NOT a
    # flag passed to the subprocess invocation; grompp writes it to disk.
    return [
        _grompp_command(stage, checkpoint_path),
        _mdrun_command(stage, config, checkpoint_path=checkpoint_path),
    ]
